spring:
  application:
    name: loan-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:2s}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/loan-platform

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:}
    password: ${RABBITMQ_PASSWORD:}
    timeout: ${RABBITMQ_TIMEOUT:2s}
  ssl:
    bundle:
      pem:
        spiffe:
          keystore:
            certificate: file:/spiffe-certs/svid.pem
            private-key: file:/spiffe-certs/svid_key.pem
          truststore:
            certificate: file:/spiffe-certs/bundle.pem

server:
  port: ${LOAN_SERVER_PORT:8080}
  ssl:
    enabled: true
    bundle: spiffe
    client-auth: need
    certificate: /spiffe-certs/svid.pem
    certificate-private-key: /spiffe-certs/svid_key.pem
    trust-certificate: /spiffe-certs/bundle.pem

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${EUREKA_INSTANCE_HOSTNAME:loan-service}
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port:  ${LOAN_SERVER_PORT}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 60
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-registry:8086/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true

resilience4j:
  timelimiter:
    instances:
      paymentTimeout:
        timeoutDuration: 2s
  retry:
    instances:
      paymentRetry:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  bulkhead:
    instances:
      paymentBulkhead:
        maxConcurrentCalls: 25
        maxWaitDuration: 0
      loanServiceBulkhead:
        maxConcurrentCalls: 10
        maxWaitDuration: 0

  circuitbreaker:
    instances:
      paymentCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3


logging:
  level:
    io.github.resilience4j.circuitbreaker: DEBUG
    org.ex.loanservice: DEBUG
