spring:
  application:
    name: loan-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:2s}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:}
    password: ${RABBITMQ_PASSWORD:}
    timeout: ${RABBITMQ_TIMEOUT:2s}

server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 60
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8086/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true

resilience4j:
  timelimiter:
    instances:
      paymentTimeout:
        timeoutDuration: 2s
  retry:
    instances:
      paymentRetry:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  bulkhead:
    instances:
      paymentBulkhead:
        maxConcurrentCalls: 25
        maxWaitDuration: 0
      loanServiceBulkhead:
        maxConcurrentCalls: 10
        maxWaitDuration: 0

  circuitbreaker:
    instances:
      paymentCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3


logging:
  level:
    io.github.resilience4j.circuitbreaker: DEBUG
    org.ex.loanservice: DEBUG
