apiVersion: apps/v1
kind: Deployment
metadata: { name: loan-decision-service }
spec:
  replicas: 1
  selector: { matchLabels: { app: loan-decision-service } }
  template:
    metadata: { labels: { app: loan-decision-service } }
    spec:
      containers:
        - name: loan-decision-service
          image: loan-decision-service:local
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8085 }]
          env:
            - { name: EUREKA_URL, value: "http://service-registry:8761/eureka/" }
            - { name: RABBIT_HOST, value: "rabbitmq" }
            - { name: REDIS_HOST, value: "redis" }
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8085 }
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata: { name: loan-decision-service }
spec:
  selector: { app: loan-decision-service }
  ports: [{ port: 8085, targetPort: 8085 }]
