spring.application.name=service-registry
server.port=8086

# Eureka

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8086/eureka/
eureka.server.enable-self-preservation=true
eureka.server.eviction-interval-timer-in-ms=5000