POST http://localhost:8000//api/v1/expenses/analyze
Content-Type: application/json

{
            "submitted_by": "John Doe",
            "currency": "INR",
            "expenses": [
                {
                    "description": "Future Flight",
                    "amount": 100.0,
                    "merchant": "Airline",
                    "category": "Travel"
                }
            ]
}