services:
  loan-service:
    profiles:
      - loan
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: loan-service

    environment:
      SERVICE: LOAN

    env_file:
      - .env.sb
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    env_file:
      - .env.sb

    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:?REDIS_PASSWORD must be set}

    volumes:
      - redis-data:/data

    command: #redis-server --appendonly yes
      - redis-server
      - --appendonly
      - "yes"
      - --requirepass
      - ${REDIS_PASSWORD:?REDIS_PASSWORD must be set}
    healthcheck:
      test: #["CMD", "redis-cli", "ping"]
        - CMD-SHELL
        - redis-cli -a "$${REDIS_PASSWORD}" --no-auth-warning ping | grep PONG
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:?RABBITMQ_USERNAME must be set}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:?RABBITMQ_PASSWORD must be set}

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

    healthcheck:
      test: #["CMD", "rabbitmq-diagnostics", "-q", "ping"]
        [
          "CMD-SHELL",
          "rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
  rabbitmq-data:

