"""initial schema

Revision ID: ddddc8be2f2d
Revises: 
Create Date: 2026-08-06 21:42:08.869555

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddddc8be2f2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('country_code')
    )
    op.create_table('daily_collection_runs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finish_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_location_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('configured_locations',
    sa.Column('location_id', sa.String(length=64), nullable=False),
    sa.Column('location_name', sa.String(length=150), nullable=False),
    sa.Column('location_type', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('state_name', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('provider_preference', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('daily_collection_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_state_representative', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.country_code'], ),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.Column('representative_location_id', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.country_code'], ),
    sa.ForeignKeyConstraint(['representative_location_id'], ['configured_locations.location_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'state_code', name='uq_states_country_state')
    )
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.String(length=64), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('observation_timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('apparent_temperature_c', sa.Float(), nullable=False),
    sa.Column('humidity_percent', sa.Float(), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=False),
    sa.Column('weather_code', sa.Integer(), nullable=False),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=False),
    sa.Column('wind_direction_deg', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('unit_system', sa.String(length=20), nullable=False),
    sa.Column('collection_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['configured_locations.location_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'observation_date', 'provider', 'collection_type', name='uq_observation_idempotency')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_observations')
    op.drop_table('states')
    op.drop_table('configured_locations')
    op.drop_table('daily_collection_runs')
    op.drop_table('countries')
    # ### end Alembic commands ###
