agent_address = "/tmp/spire-agent/public/api.sock"
cmd = ""
cert_dir = "/spiffe-certs"
svid_file_name = "svid.pem"
svid_key_file_name = "svid_key.pem"
svid_bundle_file_name = "bundle.pem"
renew_signal = ""